services:
  www:
    image: node:26.8.1-alpine
    container_name: katolika-main-website
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - www_node_modules:/app/node_modules
      - www_next_cache:/app/.next
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CI: "true"
    command: sh -c "npm install && npm run dev"


volumes:
  www_node_modules:
  www_next_cache:
